version: '3.8'
services:
  oracle-database:
    image: ekouakou/oracle-database:19.3.0-ee
    container_name: oracle-elax-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_SID=xe
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_12c
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - oracle-data:/opt/oracle/ordata
      - ./dumps:/opt/oracle/dumps
    restart: unless-stopped
    shm_size: 1g
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "/", "as", "sysdba", "@/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5m

volumes:
  oracle-data:

networks:
  default:
    driver: bridge
